name: App Tester

on:
  push:
    # branches: [ main ]
    paths:
      - '.github/workflows/tests.yml'
      - 'App/**'
      - 'tests/**'
      - 'main.py'
  pull_request:
    # branches: [ main ]
    paths:
      - '.github/workflows/tests.yml'
      - 'App/**'
      - 'tests/**'
      - 'main.py'
permissions:
  contents: read

jobs:
  testing:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Running "tests" package
      run: |
        python -m tests